// Code generated by moq; DO NOT EDIT
// github.com/matryer/moq

package eventtest

import (
	"sync"
)

var (
	lockEventProducerMockHierarchyBuilt sync.RWMutex
)

// EventProducerMock is a mock implementation of EventProducer.
//
//     func TestSomethingThatUsesEventProducer(t *testing.T) {
//
//         // make and configure a mocked EventProducer
//         mockedEventProducer := &EventProducerMock{
//             HierarchyBuiltFunc: func(instanceID string, dimensionName string) error {
// 	               panic("TODO: mock out the HierarchyBuilt method")
//             },
//         }
//
//         // TODO: use mockedEventProducer in code that requires EventProducer
//         //       and then make assertions.
//
//     }
type EventProducerMock struct {
	// HierarchyBuiltFunc mocks the HierarchyBuilt method.
	HierarchyBuiltFunc func(instanceID string, dimensionName string) error

	// calls tracks calls to the methods.
	calls struct {
		// HierarchyBuilt holds details about calls to the HierarchyBuilt method.
		HierarchyBuilt []struct {
			// InstanceID is the instanceID argument value.
			InstanceID string
			// DimensionName is the dimensionName argument value.
			DimensionName string
		}
	}
}

// HierarchyBuilt calls HierarchyBuiltFunc.
func (mock *EventProducerMock) HierarchyBuilt(instanceID string, dimensionName string) error {
	if mock.HierarchyBuiltFunc == nil {
		panic("moq: EventProducerMock.HierarchyBuiltFunc is nil but EventProducer.HierarchyBuilt was just called")
	}
	callInfo := struct {
		InstanceID    string
		DimensionName string
	}{
		InstanceID:    instanceID,
		DimensionName: dimensionName,
	}
	lockEventProducerMockHierarchyBuilt.Lock()
	mock.calls.HierarchyBuilt = append(mock.calls.HierarchyBuilt, callInfo)
	lockEventProducerMockHierarchyBuilt.Unlock()
	return mock.HierarchyBuiltFunc(instanceID, dimensionName)
}

// HierarchyBuiltCalls gets all the calls that were made to HierarchyBuilt.
// Check the length with:
//     len(mockedEventProducer.HierarchyBuiltCalls())
func (mock *EventProducerMock) HierarchyBuiltCalls() []struct {
	InstanceID    string
	DimensionName string
} {
	var calls []struct {
		InstanceID    string
		DimensionName string
	}
	lockEventProducerMockHierarchyBuilt.RLock()
	calls = mock.calls.HierarchyBuilt
	lockEventProducerMockHierarchyBuilt.RUnlock()
	return calls
}
