---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.9.0

inputs:
  - name: dp-hierarchy-builder
    path: go/src/github.com/ONSdigital/dp-hierarchy-builder

outputs:
  - name: build

run:
  path: go/src/github.com/ONSdigital/dp-hierarchy-builder/ci/scripts/build.sh