---

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.24.7-bookworm

inputs:
  - name: dp-hierarchy-builder
    path: dp-hierarchy-builder

outputs:
  - name: build

run:
  path: dp-hierarchy-builder/ci/scripts/build.sh